export const DEFAULT_BUDGET_AREAS = [
  {
    name: "Daily Life",
    categories: [
      { name: "Clothes", type: "expense" },
      { name: "Eating Out", type: "expense" },
      { name: "Fun", type: "expense" },
      { name: "Gas", type: "expense" },
      { name: "Grocery", type: "expense" },
      { name: "Health", type: "expense" },
      { name: "Subscriptions", type: "expense" },
      { name: "Cashback", type: "cashback" },
      { name: "Refund", type: "refund" },
      { name: "Return", type: "refund" },
      { name: "Other", type: "expense" },
    ],
  },
  {
    name: "My Business",
    categories: [
      { name: "Advertising", type: "expense" },
      { name: "Assets", type: "expense" },
      { name: "Commissions", type: "expense" },
      { name: "Subscriptions", type: "expense" },
      { name: "Supplies", type: "expense" },
      { name: "Travel", type: "expense" },
      { name: "Recurring", type: "income" },
      { name: "Tip", type: "income" },
      { name: "Sales", type: "income" },
      { name: "Cashback", type: "cashback" },
      { name: "Refund", type: "refund" },
      { name: "Return", type: "refund" },
      { name: "Other Expense", type: "expense" },
      { name: "Other Income", type: "income" },
    ],
  },
];
