export const DEFAULT_BUDGET_AREAS = [
  {
    name: "Daily Life",
    isDefault: true,
    categories: [
      { name: "Clothes", isDefault: false, type: "expense" },
      { name: "Eating Out", isDefault: false, type: "expense" },
      { name: "Fun", isDefault: false, type: "expense" },
      { name: "Gas", isDefault: false, type: "expense" },
      { name: "Grocery", isDefault: true, type: "expense" },
      { name: "Health", isDefault: false, type: "expense" },
      { name: "Subscriptions", isDefault: false, type: "expense" },
      { name: "Cashback", isDefault: false, type: "cashback" },
      { name: "Refund", isDefault: false, type: "refund" },
      { name: "Return", isDefault: false, type: "refund" },
      { name: "Other", isDefault: false, type: "expense" },
    ],
  },
  {
    name: "My Business",
    isDefault: false,
    categories: [
      { name: "Advertising", isDefault: false, type: "expense" },
      { name: "Assets", isDefault: false, type: "expense" },
      { name: "Commissions", isDefault: false, type: "expense" },
      { name: "Subscriptions", isDefault: false, type: "expense" },
      { name: "Supplies", isDefault: false, type: "expense" },
      { name: "Travel", isDefault: false, type: "expense" },
      { name: "Recurring", isDefault: false, type: "income" },
      { name: "Tip", isDefault: false, type: "income" },
      { name: "Sales", isDefault: false, type: "income" },
      { name: "Cashback", isDefault: false, type: "cashback" },
      { name: "Refund", isDefault: false, type: "refund" },
      { name: "Return", isDefault: false, type: "refund" },
      { name: "Other Expense", isDefault: false, type: "expense" },
      { name: "Income", isDefault: true, type: "income" },
    ],
  },
];
